<?php


/*
 * Implementation hook_menu
 */
function weeve_registration_menu() {
  $items = array();

  $items['signup'] = array(
    'title' => 'Join Weeve',
    'access callback' => 'weeve_registration_access',
    'page callback' => 'weeve_registration_page',
    'type' => MENU_NORMAL_ITEM,
  );

  $items['signup/user'] = array(
    'title' => 'Join the community',
    'access callback' => 'weeve_registration_access',
    'page callback' => 'weeve_registration_user_page',
    'type' => MENU_CALLBACK,
  );

  $items['signup/npo'] = array(
    'title' => 'Build the Community',
    'access callback' => 'weeve_registration_access',
    'page callback' => 'weeve_registration_npo_page',
    'type' => MENU_CALLBACK,
  );

  return $items;
}


/*
 * Implementation hook_theme
 */
function weeve_registration_theme() {
  return array(
    'wevee_register_page' => array(
      'template' => 'tpl/register_page'
    ),
  );
}

function weeve_registration_access() {
  global $user;
  if ($user->uid == 0) {
    return TRUE;
  } else {
    return FALSE;
  }
}

function weeve_registration_page() {
  return theme('wevee_register_page');
}

function weeve_registration_user_page() {
  $form = drupal_get_form('weeve_registration_user_form');
  // return drupal_render($form);
  return $form;
}

function weeve_registration_npo_page() {

}

function weeve_registration_user_form() {
  $form = array();

  $form['fullname'] = array(
    '#type' => 'textfield',
    '#title' => t('Full name'),
    '#descriprion' => t('Your first and last name'),
  );

  $form['email'] = array(
    '#type' => 'textfield',
    '#title' => t('Email'),
    '#descriprion' => t('Don\'t worry, you can hide this.'),
  );

  $form['password'] = array(
    '#type' => 'password',
    '#title' => t('Password'),
    '#descriprion' => t('Between 6-8 characters'),
  );

  $form['terms'] = array(
    '#type' => 'textarea',
    '#title' => '',
    '#default_value' => variable_get('', 'Terms will here'),
    '#disabled' => true,
  );

  $form['create'] = array(
    '#type' => 'submit',
    '#value' => t('Create account'),
  );

  return $form;
}

function weeve_registration_user_form_validate(&$form, &$form_state) {

}

function weeve_registration_user_form_submit(&$form, &$form_state) {

}


function weeve_registration_npo_form() {
  $form = array();


  return $form;
}