<?php

/**
 * Implements hook_pay_method_handler_info().
 */
function paypal_pay_method_handler_info() {
  return array(
    'pay_method_gateway_paypal' => array(
      'title' => t('TESTING ONLY: PayPal Website Payments Pro'),
      'description' => t('Payment processing using Paypal Website Payments Pro. This payment method is under development and currently supports credit card processing. An Express Checkout option is required for use in production.'),
      'parent' => 'pay_method_gateway',
      'module' => 'paypal',
      'path' => drupal_get_path('module', 'paypal') .'/includes/handlers',
    ),
    'pay_method_direct_paypal' => array(
      'title' => t('TESTING ONLY: PayPal Website Payments Standard'),
      'description' => t('Payment processing using Paypal Website Payments Standard. This payment method is under development and not ready for use.'),
      'parent' => 'pay_method_direct',
      'module' => 'paypal',
      'path' => drupal_get_path('module', 'paypal') .'/includes/handlers',
    ),
  );
}

/**
 * Helper function to return all available currencies for PayPal.
 * These were taken from "Table 2" on the following page:
 * https://cms.paypal.com/us/cgi-bin/?cmd=_render-content&content_ID=developer/e_howto_api_nvp_currency_codes
 */
function paypal_currencies() {
  return array(
    'AUD', // Australian Dollar.
    'CAD', // Canadian Dollar.
    'CZK', // Czech Koruna.
    'DKK', // Danish Krone.
    'EUR', // Euro.
    'HUF', // Hungarian Forint.
    'JPY', // Japanese Yen.
    'NOK', // Norwegian Krone.
    'NZD', // New Zealand Dollar.
    'PLN', // Polish Zloty.
    'GBP', // Pound Sterling.
    'SGD', // Singapore Dollar.
    'SEK', // Swedish Krona.
    'CHF', // Swiss Franc.
    'USD', // U.S. Dollar.
  );
}
