<?php
/**
 * @file
 */

/**
 * Implentation of the hook_install().
 */
function adaptive_payments_test_install() {
 }

/**
 * Implentation of the hook_uninstall().
 */
function adaptive_payments_test_uninstall() {
  for ($j = 1; $j<=6; $j++) {
    variable_del('adaptive_payments_test_receiver_use_'. $j);
    variable_del('adaptive_payments_test_receiver_'. $j);
    variable_del('adaptive_payments_test_receiver_amount_'. $j);
    variable_del('adaptive_payments_test_receiver_primary_'. $j);;
    variable_del('adaptive_payments_test_receiver_invoiceid_'. $j);
  }

    variable_del('adaptive_payments_test_memo');
    variable_del('adaptive_payments_test_trackingid');
    variable_del('adaptive_payments_test_last_paykey');
    variable_del('adaptive_payments_test_startingDate');
    variable_del('adaptive_payments_test_endingDate');
    variable_del('adaptive_payments_test_maxTotalAmountOfAllPayments');
    variable_del('adaptive_payments_test_maxNumberOfPayments');
    variable_del('adaptive_payments_test_last_preapprovalKey');
    variable_del('adaptive_payments_test_sender');
    variable_del('adaptive_payments_test_last_transactionId');
    variable_del('adaptive_payments_test_redirect_cmd');
    variable_del('adaptive_payments_test_redirect');
    variable_del('adaptive_payments_test_sandbox');
    variable_del('adaptive_payments_test_debug');
    variable_del('adaptive_payments_test_API_UserName');
    variable_del('adaptive_payments_test_API_Password');
    variable_del('adaptive_payments_test_API_Signature');
    variable_del('adaptive_payments_test_API_AppID');
    variable_del('adaptive_payments_test_returnUrl');
    variable_del('adaptive_payments_test_cancelUrl');
    variable_del('adaptive_payments_test_currencyCode');
    variable_del('adaptive_payments_test_ipnNotificationUrl');
    //I think that's it all :)
 }
